<a href="https://colab.research.google.com/github/AdnanAnwarR/practice_DS/blob/main/Hands_On_Day_Adnan_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Langkah 1 – Writing Code in Python using Jupyter Notebook / Google Colab

# ini adalah Notebook saya
ini adalah markdown saya

# print

In [25]:
#kutip satu('') atau kutip dua("") sama saja hasilnya
print("Hello World")
print('Hello World')

Hello World
Hello World

In [26]:
print(1 + 2 + 3)

6

In [27]:
print("umur saya ",1 + 2 + 3,"tahun")

umur saya  6 tahun

# indentasi

In [28]:
print("hi")
 print("hi")
  print("hi")

IndentationError: unexpected indent (3642123217.py, line 2)

# variabel

## variable angka

In [29]:
x = 7
x

7

## variable teks

In [30]:
salam = "good morning"
print(salam)

good morning

# logika if

In [31]:
if True: print("it's true")

it's true

In [32]:
if False: print("it's false")

In [33]:
jumlah_menit = 80
# jika jumlah_menit = 60 tidak akan muncul karna tidak memenuhi
if jumlah_menit > 70:
  print("harus kurangi 60")

harus kurangi 60

# logika if ... else ...

In [34]:
lampu = "nyala"
if lampu == 'nyala':
  print("lampu nyala")
else:
  print("lampu mati")

lampu nyala

# logika if ... elif ... else ...

In [35]:
lampu = "hijau"
if lampu == 'nyala':
  print("lampu nyala")
elif lampu == 'hijau':
  print("lampu hijau")
else:
  print("lampu mati")

lampu hijau

# komentar

In [ ]:
# ini komentar
a = 3
b = 7

#ubah sesuai keinginan
operasi = "kali"


if operasi == "tambah":
  print(a+b) #penjumlahan
elif operasi == "kali":
  print(a*b) #perkalian
else:
  print(a,b)

# library

In [36]:
import math
#membulatkan bilngan ke bawah
print(math.floor(3.14))

3

In [37]:
import sys
# mengembalikan versi python yang sedang dipakai
print(sys.version)

3.12.13 (main, Mar  4 2026, 09:23:07) [GCC 11.4.0]

In [38]:
import pandas
pandas.DataFrame()

Empty DataFrame
Columns: []
Index: []

In [39]:
import pandas as pd
pd.DataFrame()

Empty DataFrame
Columns: []
Index: []

#input

In [40]:
nama = input()

adnan

In [41]:
print(nama)

adnan

In [45]:
umur = input("masukkan umur kamu:")
umur = int(umur)

masukkan umur kamu:20

In [46]:
print(umur)

20

In [47]:
umur + 20

40