<a href="https://colab.research.google.com/github/AdnanAnwarR/practice_DS/blob/main/Hypothesis_Testing_Hands_On_Day__10_Adnan_ipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd #Python for Data Analysis
from scipy.stats import ttest_ind #SCIENTIFIC PYTHON(scipy)
from scipy.stats import chisquare #scientific python for testing using chi square
from scipy.stats import f_oneway #scientific python for testing using anova one way

In [2]:
# Nilai ujian siswa
# H0: Rata-rata nilai kelas konvensional = kelas digital
# H1: Rata-rata nilai kelas digital > kelas konvensional
kelas_konvensional = [65, 70, 72, 68, 75, 74, 71, 69, 73, 70]
kelas_digital = [75, 78, 80, 77, 82, 79, 76, 81, 78, 80]

In [3]:
t_stat, p_value = ttest_ind(
    kelas_digital,
    kelas_konvensional,
    # alternative='greater'
)

print("T-Statistic:", t_stat)
print("P-Value:", p_value)

T-Statistic: 6.71681938499185
P-Value: 2.6859103698547314e-06

In [4]:
alpha = 0.05

In [5]:
# Jika p-value < 0,05, maka dapat disimpulkan bahwa metode pembelajaran digital interaktif secara statistik meningkatkan rata-rata nilai siswa dibandingkan metode konvensional.
if p_value < alpha:
    print("Tolak H0: Metode digital meningkatkan nilai siswa")
else:
    print("Gagal menolak H0: Tidak ada bukti peningkatan nilai")

Tolak H0: Metode digital meningkatkan nilai siswa

In [6]:
data = {
    "Metode": ['A','A','A','B','B','B','C','C','C'],
    "Nilai": [78,80,85,70,73,75,90,92,91],

}

df = pd.DataFrame(data)
df

  Metode  Nilai
0      A     78
1      A     80
2      A     85
3      B     70
4      B     73
5      B     75
6      C     90
7      C     92
8      C     91

In [7]:
df.groupby("Metode")["Nilai"].mean()

Metode
A    81.000000
B    72.666667
C    91.000000
Name: Nilai, dtype: float64

In [8]:
nilai_a = df[df["Metode"]== "A"]["Nilai"]
nilai_b = df[df["Metode"]== "B"]["Nilai"]
nilai_c = df[df["Metode"]== "C"]["Nilai"]

In [9]:
nilai_c

6    90
7    92
8    91
Name: Nilai, dtype: int64

In [10]:
f_stat, p_value = f_oneway(nilai_a,nilai_b,nilai_c)

In [11]:
print("F-Statistic:", f_stat)
print("P-Value:", p_value)

F-Statistic: 37.29508196721315
P-Value: 0.00041267449978743965